networks:
  app-network:
    driver: bridge
services:
  db_pg:
    image: postgres:15
    container_name: postgres
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    networks:
      - app-network
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    ports:
      - 27017:27017
